Include shell completion for Cargo
rust-lang/rustup pull request #1425
Opened 2018-06-02 01:05 UTC by ricvelozo

*   Include shell completion for Cargo on `rustup completions` (#387,  rust-lang/cargo#5596)
*   Add argument to show only the default toolchain: `rustup toolchain list --default` (#450)
*   Update the `rustup completions bash` instructions to use home directory (#1199)

2018-06-09 23:23 UTC, Diggsey requested changes
Thanks for the PR! There are however a few changes needed before I'd be happy accepting it.

2018-06-09 23:23 UTC, Diggsey commented on src/rustup-cli/rustup_mode.rs
> +                let prefix = "~/.rustup/toolchains/$(rustup toolchain list --default)";
This prefix is not correct - rustup is not necessarily installed here, and the default toolchain isn't necessarily correct.

To get the installation directory of the active toolchain, you should use `rustc --print sysroot`

2018-06-09 23:23 UTC, Diggsey commented on src/rustup-cli/rustup_mode.rs
> +                match shell {
Non-trivial logic like this should be pulled out into its own function.

2018-06-09 23:23 UTC, Diggsey commented on src/rustup-cli/rustup_mode.rs
> +                .subcommand(
This change should not be necessary

2018-06-09 23:23 UTC, Diggsey commented on src/rustup-cli/common.rs
> +pub fn list_toolchains(cfg: &Cfg, m: &ArgMatches) -> Result<()> {
Please revert the changes to this file as they should not be necessary.

2018-06-10 00:53 UTC, ricvelozo commented on src/rustup-cli/rustup_mode.rs
> +                .subcommand(
You're requesting to remove the new `--default` arg?

2018-06-10 01:04 UTC, ricvelozo commented on src/rustup-cli/rustup_mode.rs
> +                let prefix = "~/.rustup/toolchains/$(rustup toolchain list --default)";
Does to replace the `rustup toolchain list --default` for `rustc --print sysroot` solves the problem? I have no way to know the toolchain that the user is using, just the default.

2018-07-07 23:14 UTC, ricvelozo commented on src/rustup-cli/rustup_mode.rs
> +                let prefix = "~/.rustup/toolchains/$(rustup toolchain list --default)";
@Diggsey Help me to finish this, please.

2018-08-30 12:27 UTC, Kerollmops commented on src/rustup-cli/rustup_mode.rs
> +                let prefix = "~/.rustup/toolchains/$(rustup toolchain list --default)";
`rustc --print sysroot` will call the binary of the currently used toolchain.

2019-01-14 00:55 UTC, nrc commented
Closing due to lack of activity and reviewer bandwidth.

2019-01-14 00:55 UTC, closed without merging