Add x86_64-unknown-linux-musl build support
rust-lang/rustup pull request #1517
Opened 2018-09-26 06:35 UTC by martell

WIP

2018-10-17 19:04 UTC, strfry commented
@martell Please regard my additional commit 54b50f5d2454a9ba86eb3230c1a20cd0b0937590 in #1527 .
The Dockerfile must describe a normal glibc-distro with musl-capabilities for this build system to work.

What else is needed to make rustc appear in x86_64-unknown-linux-musl flavor?

2018-10-17 20:55 UTC, martell commented
Hey @strfry,

First, thanks for the help :)
I thought no one was interested in this but me.

> The Dockerfile must describe a normal glibc-distro with musl-capabilities for this build system to work.
Why does it need to describe a glibc system with musl-capabilities?
Can it not just use a musl distro directly like in my dockerfile?

> What else is needed to make rustc appear in x86_64-unknown-linux-musl flavor?
I'm not sure, I upstreamed a few commits from musl / alpine needed changes into llvm 5.0 which was 2 releases ago now in the hopes that later we could get rustup support for alpine.
I think for build systems making minimal alpine rust containers it would be better than using the package manager.
@alexcrichton could weigh in with some direction/feedback?

Best,
Martell

2018-10-18 04:04 UTC, strfry commented
@martell ,

I started out with just adding bash (and then later rustc and cargo), but the way this is supposed to work is that the rustc is passed in through a Docker volume from the Travis host system. And that doesn't work when the container is a different architecture than the host distro.
What finally worked was to adapt one of the other Dockerfiles and install musl-tools a as the cross-compiler. The build will try call musl-gcc at some point, seems like someone already figured this out ;)


The other part i ment is getting rust itself to compile x86_64-musl as a host architecture, so that it's provided for rustup to download.
I opened rust-lang/rust#55163 and ran into some issues.

2018-10-18 13:25 UTC, alexcrichton commented
@martell I think it's probably not worth doing this until we get a musl host rustc working, otherwise this rustup won't have anything to download! When it works though it'll be easiest to compile a static rustup here, just using cross compilation from a glibc environment to `x86_64-unknown-linux-musl` which will produce a statically linked binary

2019-01-16 22:26 UTC, kinnison commented
@martell Do you think you want to keep this PR open for now, or should we close it off and perhaps just leave #1053 to track this?

2019-01-30 07:57 UTC, dwijnand commented
Seeing as #1053 is blocked on upstream https://github.com/rust-lang/rust/issues/57439, I think it makes sense to close this PR in the meantime.  Please note that a closed PR isn't a rejected PR, the work here can be reused and resubmitted.

2019-01-30 08:51 UTC, martell commented
Sorry for the delay, I'll close this for now until the host support has been resolved.

2019-03-18 13:40 UTC, mati865 commented
IIUC this needs `cfg` similar to the one for MIPS:
https://github.com/rust-lang/rustup.rs/blob/819ddda6b7fc1f18884f027f646cd8714f8c4e9a/src/dist/dist.rs#L178

2019-03-22 18:16 UTC, martell commented
I will add this over the weekend but @mati865 you should feel free to hijack this PR if you do not want to wait.
You finished up the rustc and cargo support along with the forge stuff and I think you deserve more that anyone to be the one who enables it in rustup :)

2019-03-23 05:14 UTC, martell commented
@alexcrichton soft ping

2019-03-25 14:13 UTC, alexcrichton commented
Ah oops thanks for the ping. I'm not sure the container will work here though since it's primarily used with glibc toolchains, although you can edit .travis.yml to see the failure on the PR. Could the build be configured to do a cross build from a glibc toolchain to a musl toolchain?

2019-04-30 15:46 UTC, rye commented on .travis.yml
> +    - { <<: *linux, env: SKIP_TESTS=1 TARGET=x86_64-unknown-linux-musl       }
I was slightly confused at first by the `.travis.yml` file, but I think I understand what is meant.

While this PR has an inclusion to `.travis.yml` of a new TARGET to the matrix which _does_ get expanded with `if: branch != master`, for _PR builds_ on Travis, `branch` expands to the base branch for the PR.  Obviously, `master != master` is false, so this job isn't run and hence the PR is basically testing the functionality of what's on `master`.

So to actually test these changes prior to merging, the only change required would be to (temporarily) hand-code the matrix addition to always run? That might look something like:

```suggestion
    - { <<: *linux, env: SKIP_TESTS=1 TARGET=x86_64-unknown-linux-musl       }
    - { os: linux, env: SKIP_TESTS=1 TARGET=x86_64-unknown-linux-musl        }
```

(My suggestion would not be ideal to ship, but would illuminate any build failures.)

2019-05-18 21:51 UTC, martell commented
Following up here, sorry things have been slow.
Finally got some time this weekend to have another look.

@alexcrichton we appear to have an issue using a glibc distro like ubuntu cross building to the musl target.

instead of a binary called ldd we have musl-ldd in these environments.
using alpine or void linux directly is much easier to work with because of this.

```bash
/# ldd --version
ldd (Ubuntu GLIBC 2.27-3ubuntu1) 2.27
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.

/# musl-ldd --version
musl libc (x86_64)
Version 1.1.19
Dynamic Program Loader
Usage: musl-ldd [options] [--] pathname
```

cross compiling also results in this with the current build system.
`error: failed to run `rustc` to learn about target-specific information`
The travis build history with the various methods should reflect this.
cc @rye

2019-05-19 00:45 UTC, martell commented
Finally got some time this weekend to have another look.

@alexcrichton I believe this should be mergeable now.
When you approve I will drop 44ddbe9 from the PR

Thanks again for the suggestion @rye.

2019-05-19 01:06 UTC, rye commented
@martell, no problem, and thank you for doing this! It at least certainly seems that [#3396.2](https://travis-ci.com/rust-lang/rustup.rs/jobs/201283144) (musl build) was successful and did use the appropriate target! Can't wait to use rustup in my Alpine environments soonish. 😄

2019-05-19 09:05 UTC, kinnison reviewed
I'm not in a position to review the musl-specific bits, but one comment I do have is regarding the docker machine.

@lzutao put a lot of effort into allowing us to reuse the Rust compiler docker images in order to ensure that we were matching libcs etc wherever possible.  Is there a suitable rust-compiler docker for musl to save the creation of the docker from ubuntu?

2019-05-19 09:20 UTC, lzutao commented
@kinnison Yes, Rustc has [`dist-x86_64-musl` dockerfile][1]. I don't test it yet
but it's worth a try.

[1]: https://github.com/rust-lang/rust/blob/master/src/ci/docker/dist-x86_64-musl/Dockerfile

2019-05-19 21:07 UTC, kinnison commented
@lzutao Do you think you could look at what's been done on this PR and then see if you can come up with a proposed patch to reuse the rustc docker if appropriate?

2019-05-20 15:00 UTC, alexcrichton commented
This all looks good to me, thanks @martell!

@kinnison FWIW musl is pretty special in that it doesn't require the same docker containers as other targets. The main difference is that the musl target is by default statically linked instead of having a dependency on a dynamically linked libc. For glibc platforms you need a special toolchain for targeting a really old glibc (which is our goal in rust-lang/rust and what rustup wants to mirror), but for musl there's no need since any toolchain can produce a workable binary!

In that sense this should be good to go IMO w/o docker changes.

2019-05-20 17:27 UTC, martell commented
Awesome, I'm happy to do any docker changes as a follow up if anyone wishes.
I did actually try `FROM rust-x86_64-unknown-linux-musl` but that did not exist.
We can create one if needed. Anyone have a specific issue they want to create for this?

@alexcrichton I do not have permission to merge.
I did however remove the ci testing commit as promised.
Can you merge?

2019-05-20 17:52 UTC, tesuji reviewed
The PR might still fail because of missing sccache.

2019-05-20 17:52 UTC, lzutao commented on src/dist/dist.rs
> +const TRIPLE_X86_64_UNKNOWN_LINUX: &'static str = "x86_64-unknown-linux-gnu";
Remove `'static`. We don't need it anymore.

2019-05-20 17:52 UTC, lzutao commented on src/dist/dist.rs
> +const TRIPLE_X86_64_UNKNOWN_LINUX: &'static str = "x86_64-unknown-linux-musl";
Same

2019-05-20 17:53 UTC, lzutao commented on ci/docker/x86_64-unknown-linux-musl/Dockerfile
> +  gcc
Install sccache here: https://github.com/mozilla/sccache/releases/tag/0.2.8
Just download and extract it in PATH

2019-05-20 21:49 UTC, alexcrichton commented
Note that I'm personally just commenting here, I'm leaving the final review up to @kinnison

2019-05-21 11:03 UTC, kinnison commented
If there's no value in using the rustc docker for now, then I'll wait on the `sccache` comment responses before I make a decision.

2019-05-22 23:10 UTC, martell commented
@kinnison done :)
Same deal as before, once approved I will remove the travis change commit.
Ahh damn, I was a few hours late to make the next rustup release :/

2019-05-23 01:53 UTC, lzutao commented
@martell You could use [ci/docker/android/Dockerfile][1] as an example to 
install sccache.

[1]: https://github.com/rust-lang/rustup.rs/blob/master/ci/docker/android/Dockerfile

2019-05-23 09:23 UTC, kinnison commented
The appveyor failure is spurious (possibly due to too many parallel tests at once?)

2019-05-23 10:08 UTC, lzutao commented
I pushed some changes to [my branch](https://github.com/lzutao/rustup.rs/tree/musl-x86_64). You could cherry-pick it to your PR.

2019-05-25 10:38 UTC, tesuji requested changes
Edit `ci/cloudfront-invalidation.txt` and add musl targets.

2019-05-25 19:16 UTC, kinnison commented
> Edit `ci/cloudfront-invalidation.txt` and add musl targets.

It's not entirely clear if the cloudfront invalidation would be necessary, but it can't hurt to have it amended.

2019-05-29 03:29 UTC, lzutao commented
Ok, I take it at #1882

2019-05-29 16:47 UTC, martell commented
Thanks @lzutao, sorry for being slow here, my time has been very restricted over the last week.

2019-05-29 16:47 UTC, closed without merging