Install some GitHub issue templates
rust-lang/rustup pull request #1625
Opened 2019-01-27 15:42 UTC by dwijnand

I've had good experiences using issue templates, and these are derived from the ones established in the cargo repo.  WDYT?

2019-01-29 16:29 UTC, dwijnand commented
WDYT @kinnison?

2019-01-29 21:40 UTC, kinnison requested changes
Over all I like the idea of having some templates.  It might be nice to have a PR template later too but this is an excellent start.

With the changes I have suggested, I'd have no problem giving a :+1:

2019-01-29 21:40 UTC, kinnison commented on .github/ISSUE_TEMPLATE/bug_report.md
> +Output of `rustc --version`:
I think rather than `rustc --version` it might be better to have `rustup show` output

2019-01-29 21:40 UTC, kinnison commented on .github/ISSUE_TEMPLATE/bug_report.md
> +<!-- (e.g rust version, OS platform/distribution/version, target toolchain(s), release channel.. -->
This would be covered by the `rustup show` output

2019-01-30 07:08 UTC, dwijnand commented
Thanks, @kinnison.  All done.

2019-02-03 09:39 UTC, kinnison approved these changes
LGTM

2019-02-07 20:29 UTC, dwijnand commented
r? @nrc

2019-02-10 05:43 UTC, nrc approved these changes

2019-02-10 05:43 UTC, merged

2019-02-10 05:43 UTC, nrc commented
SGTM, thanks!