Filtering of `component list` by available, required, and installed
rust-lang/rustup pull request #1635
Opened 2019-02-04 02:28 UTC by lazorgator

Allows filtering of `rustup component list` command.

Example output:
```console
canis@latrans$ rustup component add clippy
canis@latrans$ rustup component list --filter installed
cargo-x86_64-unknown-linux-gnu (default)
clippy-x86_64-unknown-linux-gnu (installed)
rust-docs-x86_64-unknown-linux-gnu (default)
rust-std-x86_64-unknown-linux-gnu (default)
rustc-x86_64-unknown-linux-gnu (default)
canis@latrans$ rustup component list --filter required
cargo-x86_64-unknown-linux-gnu (default)
rust-docs-x86_64-unknown-linux-gnu (default)
rust-std-x86_64-unknown-linux-gnu (default)
rustc-x86_64-unknown-linux-gnu (default)
canis@latrans$ rustup component list --filter available
llvm-tools-preview-x86_64-unknown-linux-gnu
rls-x86_64-unknown-linux-gnu
rust-analysis-x86_64-unknown-linux-gnu
rust-src
...
```

2019-02-04 21:16 UTC, kinnison commented
Hi @lazorgator,

Thanks for your contribution to Rustup.  Could you please confirm if this is just a wishlist feature from you, or is there an issue already filed which you think you're addressing with this commit?  If there's the latter then I'd really like to see the commit mention it.

Also, thank you for including a test for the feature, but it'd also be helpful if you could write a small section for `README.md` which details the filters, and also what it means for a component to be required or not.

If you aren't comfortable writing that then let me know, I wouldn't block the feature purely on that, but it'd be super-nice to have.

2019-02-05 01:46 UTC, lazorgator commented
Hi there @kinnison ,

I actually noticed this wasn't implemented from hacking on rustup for the past couple days and implemented it as a feature off-hand. If that's not okay due to concerns about feature creep, it's fine if it's not merged. I can work on the README entry for it, most certainly.

2019-02-05 21:09 UTC, kinnison requested changes
Slight wording change to point the user at `--toolchain` and I think this will be golden.

2019-02-05 21:09 UTC, kinnison commented on README.md
> +using the `rustup toolchain default <toolchain>` command. If you want to see a list of the
I'd split these two sentences and put, in between them, something like "You can use the \`--toolchain\` argument to add a component to a specific toolchain."

2019-02-05 21:09 UTC, kinnison commented on README.md
> +`export http_proxy=proxy.example.com:1080` (and likewise for HTTPS).
Again, a whitespace whoopsie.  Please unfix this so the unrelated hunk isn't in this PR.

2019-02-05 23:29 UTC, das-sein commented
@kinnison Added mention of `--toolchain` flag for `rustup component add` and removed unrelated whitespace hunk.

2019-02-07 20:57 UTC, kinnison approved these changes
LGTM.

r? @dwijnand

2019-02-10 08:11 UTC, lazorgator commented
@kinnison @nrc Merge conflict resolved.

2019-02-10 08:46 UTC, lazorgator commented
Messed up the PR. README changes overwritten. I'll close this now in favor of a new PR on top of the 2018 Edition changes :<

2019-02-10 08:46 UTC, closed without merging