Prevent uninstall of only remaining toolchain
rust-lang/rustup pull request #1636
Opened 2019-02-04 08:18 UTC by lazorgator

Behavior: should the user attempt to uninstall their only remaining toolkit, an error will be produced telling them this is not possible to do. If uninstall is allowed, rustup enters a bad state as demonstrated in #1631

This still allows for `--default-toolchain none` during install.

2019-02-04 21:23 UTC, kinnison requested changes
Fundamentally looks reasonable.  Two tiny typos in comments, so not block-worthy, but...

I'd like to see a `README.md` update because while this is fixing an unpleasant corner case of behaviour, it does now prevent something which was previously possible.  It looks like there isn't a dedicated uninstallation section of the README so I'd be satisfied by something like `(you may not uninstall the only toolchain installed)` appended to the line mentioning `rustup toolchain uninstall` in the README.

My remaining concern is that if someone had rustup installed somewhere with room for only one toolchain, they'd be unable to switch from (say) nightly to stable without uninstalling rustup entirely should this change be merged.  I'm not sure how I feel about this.

2019-02-04 21:23 UTC, kinnison commented on tests/cli-v1.rs
> +        // Can't uninstall the only toolkit left
I think you mean tool*chain* here, rather than tool*kit*

2019-02-04 21:23 UTC, kinnison commented on tests/cli-v2.rs
> +        // Can't uninstall the only toolkit left
Ditto here, tool*chain* not tool*kit*

2019-02-05 01:48 UTC, lazorgator commented
@kinnison Excellent point. I had not even considered that scenario. I wonder if this means there should be an in-place switch command in addition to this change? Maybe there's another way to address this undesirable behavior.

2019-02-05 21:06 UTC, kinnison requested changes
One tiny nit left to pick :D  Otherwise :+1:

2019-02-05 21:06 UTC, kinnison commented on README.md
> +`export http_proxy=proxy.example.com:1080` (and likewise for HTTPS).
While I dislike the trailing whitespace too, this hunk is unnecessary in the diff

2019-02-05 21:06 UTC, kinnison commented on README.md
> +`rustup toolchain uninstall nightly` | Uninstall a given toolchain (you cannot uninstall the only toolchain left installed)
:+1:

2019-02-05 21:07 UTC, kinnison commented
I don't think the undesirable situation is enough to block this, but it's certainly worth filing an issue for discussion once this PR lands.

2019-02-05 22:28 UTC, das-sein commented on README.md
> +`export http_proxy=proxy.example.com:1080` (and likewise for HTTPS).
No worries. Nits are there to pick. Why not aim for perfection.

2019-02-05 23:21 UTC, lazorgator commented
@kinnison Unrelated hunks removed from commit and force-pushed to avoid creating a superfluous commit in the history.

And yeah I'm not entirely sure this is the best solution, but it should solve the undesirable state. Hopefully a discussion comes about and some more ideas come up.

2019-02-07 20:56 UTC, kinnison commented
I think the three commits might squash nicely into two.  One for the code and one for the README, if you don't mind doing that.

2019-02-08 10:24 UTC, lazorgator commented
@kinnison Squashed the code commits and left the README commit

2019-02-10 07:56 UTC, nrc commented
Could you explain why you want to do this instead of fixing the behviour when the last toolchain is uninstalled? It seems reasonable to me to want to uninstall all toolchains

2019-02-10 08:05 UTC, lazorgator commented
@nrc I was thinking from a user perspective that it would be more confusing to enter this bad state than it would be to not enter it. It also seemed to me a bit odd that uninstalling all the toolchains would be desirable, since without any toolchains, why have rustup installed at all? If this is totally undesirable, I can work on a proper fix for the logic that causes the bad state instead.

2019-02-11 09:05 UTC, nrc commented
>  since without any toolchains, why have rustup installed at all?

I was imagining it would be a  temporary state of affairs, possibly performed by a script?

2019-02-11 15:38 UTC, lazorgator commented
@nrc Good point! I don't have any response to that, it is a scenario I hadn't considered. I could say that's dirty, but I think I agree that it should be possible for a script to be dirty without causing a bad state. I'll close this PR in a day, just in case anyone wants to chime in, and try to come up with a better solution.

2019-02-11 21:06 UTC, In-line commented on src/rustup-cli/errors.rs
> +        ToolchainUninstallOnly(t: String) {
Maybe `UninstallLastToolchain`?

2019-02-11 21:07 UTC, In-line commented on src/rustup-cli/rustup_mode.rs
> +            // Do not allow removal of toolchain if it's the only toolchain
Maybe `Do not allow removal of the last toolchain`?

2019-02-11 21:08 UTC, In-line commented on tests/cli-misc.rs
> +        // Have to have at least one toolchain left before attempting to uninstall
Maybe `Must have at least ....`?

2019-02-12 02:47 UTC, closed without merging