Bring output of `rustup show active-toolchain` and `rustup default` into line with rest of rustup
rust-lang/rustup pull request #1654
Opened 2019-02-12 10:18 UTC by lazorgator

This resolves: #1406, and brings into line the fix for #1633 

#1406 seems to just be the result of the `rustup show active-toolchain` command not producing the same output as `rustup show`, which includes the override reason. This has been changed so that if `active-toolchain` returns an override, it states the reason for the override. The change to `rustup default` is just to bring its output into line with the rest of rustup in using the "\<toolchain\> (\<status\>)" format.

Previous behavior of `rustup show active-toolchain` while nightly override is set:

```shell
canis@latrans:~/rustup.rs$ rustup show active-toolchain
nightly-x86_64-unknown-linux-gnu
```

New behavior:

```shell
canis@latrans:~/rustup.rs$ rustup show active-toolchain
nightly-x86_64-unknown-linux-gnu (directory override for '/home/canis/rustup.rs')
```

2019-02-16 21:35 UTC, kinnison requested changes
This looks good though I'd like to know why we don't have a test affected by half the patch?

Is there an opportunity to add a test for `rustup default` ?

2019-02-16 23:20 UTC, lazorgator commented
@kinnison Good point! I did also think it odd, but didn't want to add an unnecessary test in case it was intentional. I'll work on some.

2019-02-18 21:26 UTC, lazorgator commented
@kinnison Test for `show-active` with override added.

2019-02-28 20:33 UTC, kinnison approved these changes
LGTM, thanks for the test.

2019-02-28 20:33 UTC, merged