WIP: Check for stray hash when installing a toolchain
rust-lang/rustup pull request #1801
Opened 2019-04-24 16:16 UTC by Glamhoth

#1777 
As @kinnison explained - problem is in update-hash that is still present after manual removal of a toolchain. This resulted in the inability to install it again. To fix this problem we now check if there is a stray hash, and delete if so. This is WIP as a test must be written.

2019-04-24 18:35 UTC, kinnison commented
Hi @Glamhoth 

We do indeed need to try and organise a test now, because without a suitable test we be able to protect against this kind of thing causing a problem elsewhere in the future.

Do you think you're able to work out where to fit one in?

2019-04-25 07:48 UTC, Glamhoth commented
Sure, I'll try to write it today

2019-04-26 07:13 UTC, kinnison requested changes
Pretty good over-all, thank you.

It'd be nice to make the test a little less brittle though -- see my comments.

2019-04-26 07:13 UTC, kinnison commented on tests/cli-v2.rs
> +        println!("Update-hash path: {}", hash_path.display());
This println seems superfluous debugging.  Probably remove it now you're satisfied?

2019-04-26 07:13 UTC, kinnison commented on tests/cli-v2.rs
> +        expect_ok_ex(
The use of `expect_ok_ex` means you are very brittle against the exact output of the tool.

Instead I'd look to use `expect_stdout_ok` to check for the warning, and then possibly `expect_ok` to check that `rustc --version` works for the toolchain.  That way you can demonstrate that (a) the warning is emitted and (b) the toolchain got installed, without being brittle against the exact output.

2019-04-29 09:28 UTC, Glamhoth commented
I cleaned up the test.

2019-04-29 09:59 UTC, kinnison approved these changes
LGTM, thank you @Glamhoth

2019-04-29 09:59 UTC, merged