Add listing of installed targets
rust-lang/rustup pull request #1808
Opened 2019-04-25 15:31 UTC by onatm

This feature adds the ability to list installed `targets` only.

I'm playing with cross-compilation a lot and I need a way to list only the installed `targets`.

2019-04-25 18:56 UTC, kinnison requested changes
Hi!

Thanks for this patch, it looks pretty OK but it needs a test and possibly some README updates to complete the work.

Do you think you can see how to write a test for this?

2019-04-25 20:47 UTC, onatm commented
Hey!

Thank you for the review. I believe I need to add tests to `tests/cli-exact.rs`, `tests/cli-v2.rs` and `tests/cli-rustup.rs`.

Something similar to:

https://github.com/rust-lang/rustup.rs/blob/7afe6a8b10b4e5f891e1b5232a7c362b40f5c168/tests/cli-exact.rs#L354-L371

Do you think that I am heading to the right direction?

2019-04-25 22:29 UTC, onatm commented
I think I managed to implement all the required tests. I am not sure about README updates. Could you point me the place to make documentation changes @kinnison ?

I've got a question about the number of commits: Should I leave as is or squash them into one?

2019-04-26 07:05 UTC, kinnison approved these changes
Hi,

The added tests look excellent, thank you very much!

I'm happy with the commits as they are, or you could squash the three test commits into one.

Either way, I'll look to merge this in soon, unless anyone else objects.

Thanks again,

D.

2019-04-26 12:20 UTC, onatm commented
I squashed test commits into one 🎉 

I hope this feature will be useful for others as well. Thanks for the review again.

2019-04-26 20:32 UTC, tesuji approved these changes

2019-04-27 08:20 UTC, kinnison approved these changes
The squash looks clean

2019-04-27 08:20 UTC, merged