Document (some) caveats when developing Rust on Windows
rust-lang/rustup pull request #1909
Opened 2019-06-23 20:09 UTC by bltavares

This commit documents errors that a developer might face when compiling Rust projects on Windows 10.

It is by far not a comprehensive list of errors and solutions, but its a start, and document the errors I've faced when trying to compile https://github.com/rust-lang/www.rust-lang.org on Windows 10, on two scenarios:

- Fresh `rustup` installation, following the instructions on screen, and installing VS Build Tools 2019
- Older installation of `rustup`, using VS Build Tools 2017

It is important to also be aware that following the instructions of installing VS Build Tools 2019 might require patches on `*-sys` crates, as their `build.rs` might not work for the new locations on the new edition of MS Build Tools. For example: https://github.com/compass-rs/sass-rs/pull/49

2019-06-24 10:42 UTC, kinnison requested changes
These looks useful, though I have no way of knowing if they're right.  Fix the changes and I'd be okay to include this in the README, though perhaps there may also be other places worth spreading this information to?

2019-06-24 10:42 UTC, kinnison commented on README.md
> +Selecting the Build Tools instalation instead of the complete Visual Studio
Perhaps "Selecting only the _Build tools_ instead of a complete installation of Visual Studio..." instead?

2019-06-24 10:42 UTC, kinnison commented on README.md
> + <summary><code>error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.</co
Does `<Import>` need escaping here?

2019-06-24 10:42 UTC, kinnison commented on README.md
> + - Use `vcvars64.bat` instead of `vsvars32.bat` to configure the environment
is the `vc` vs. `vs` here correct (in the batch filenames)

2019-06-24 23:11 UTC, bltavares commented
@kinnison I would be completely ok to put this somewhere else as well. I've thought that this could be one of the most likely places where people would search when getting started with Rust, but if there is a suggestion to put this information elsewhere I would be fine as well.

I've adopted the changes proposed.

2019-06-25 06:01 UTC, kinnison commented
I like the content now.  Could you please squash into one commit and then it can be merged.

2019-06-25 06:06 UTC, rbtcollins reviewed
I think this belongs in one of:
 - rust-lang README.md 
 - cargo's README.md 
 - the rust book

2019-06-25 06:21 UTC, kinnison commented
@rbtcollins Any of those locations would also be good yes.  Do you object to this going into *our* readme as well?

2019-06-27 09:44 UTC, rbtcollins commented
A little yes, because I think having the content scattered around rather than in one place is misleading for folk (like I was just recently) - who finding one nugget in an official-like location may incorrectly assume that that location is authoritative and comprehensive.

2019-06-28 15:36 UTC, kinnison commented
Regarding the point about authority and comprehensiveness I understand and agree to at least some extent.  @bltavares do you think you could persue some other places which might be better for this content?  I'm happy to keep this PR here until you have had a chance to see if there's a better home for this, and then if you cannot find a better place, we'll consider whether we could house it short term with some kind of caveat to mitigate Robert's concerns.

2020-01-10 08:41 UTC, kinnison commented
Hi @bltavares 

Happy new year!

I was wondering if you might have time/energy to continue this work?  I'd still like to see this kind of thing documented, but I don't know if you made any progress getting it into any of the other locations that @rbtcollins suggested.

If you simply don't have the time/energy then that's fine, but if you could let us know that'd be helpful.

Thanks,

Daniel.

2020-01-10 14:10 UTC, bltavares commented
Hi @kinnison,

I have not yet tried to move this to either cargo, rust-lang or the book. Sorry about that.

I could try to open a similar PR on the book regarding the setup, as this seems to be a better place to group such kind of information given the discussion. I will try to do that during the weekend, and update here with the reference.

2020-04-26 20:06 UTC, kinnison commented
@bltavares This needs rebasing onto current master
@rbtcollins It looks like the book rejected it as content, should we consider taking it on?

2020-06-29 21:33 UTC, closed without merging