Update notification for removing component
rust-lang/rustup pull request #2016
Opened 2019-09-25 19:54 UTC by BeniCheni

Fixes #1993. (Previously reviewed in #2012 and corrected based on comment in this new PR)

Use a shared `parse_remove_component_notification` function to parse the notification for both `RemovingComponent` and `RemovingOldComponent`, which will essentially correct to "removing previous version of component".

###### Local Test

```sh
→ rustup update               
info: syncing channel updates for 'stable-x86_64-apple-darwin'
info: syncing channel updates for 'nightly-x86_64-apple-darwin'
info: latest update on 2019-09-25, rust version 1.39.0-nightly (6ef275e6c 2019-09-24)
info: downloading component 'clippy'
info: downloading component 'rustfmt'
info: downloading component 'rustc'
 60.1 MiB /  60.1 MiB (100 %)   7.6 MiB/s in  7s ETA:  0s
info: downloading component 'rust-std'
172.7 MiB / 172.7 MiB (100 %)   7.9 MiB/s in 22s ETA:  0s
info: downloading component 'cargo'
info: downloading component 'rust-docs'
 11.8 MiB /  11.8 MiB (100 %)   7.6 MiB/s in  1s ETA:  0s
info: downloading component 'rust-src'
info: removing previous version of component 'clippy'
info: removing previous version of component 'rustfmt'
info: removing previous version of component 'rustc'
info: removing previous version of component 'rust-std'
info: removing previous version of component 'cargo'
info: removing previous version of component 'rust-docs'
info: removing previous version of component 'rust-src'
info: installing component 'clippy'
info: installing component 'rustfmt'
info: installing component 'rustc'
 60.1 MiB /  60.1 MiB (100 %)   7.6 MiB/s in  8s ETA:  0s
info: installing component 'rust-std'
172.7 MiB / 172.7 MiB (100 %)  15.2 MiB/s in 10s ETA:  0s
info: installing component 'cargo'
info: installing component 'rust-docs'
 11.8 MiB /  11.8 MiB (100 %)   2.3 MiB/s in  4s ETA:  0s
info: installing component 'rust-src'
info: checking for self-updates

  stable-x86_64-apple-darwin unchanged - rustc 1.37.0 (eae3437df 2019-08-13)
   nightly-x86_64-apple-darwin updated - rustc 1.39.0-nightly (6ef275e6c 2019-09-24)
```

2019-09-25 20:16 UTC, thedrow requested changes
Again, there's a difference between the cases.
`RemovingComponent` should be for the `rustup component remove` command.
`RemovingOldComponent` should printed for the `rustup update` command.
The messages should be different.

2019-09-26 03:04 UTC, BeniCheni commented
@thedrow, thanks for explaining. [aaad735](https://github.com/rust-lang/rustup.rs/pull/2016/commits/aaad735aa83af36d804b3be7feefd2482f3835dd) updated to use a different approach w. `update_from_dist` param.

2019-09-26 16:43 UTC, thedrow approved these changes
LGTM.

2019-09-26 21:04 UTC, BeniCheni commented
Tiny note that [5d2b43d]() simply rename to `explicit_modify` param, which seems more explicit than previous ~`update_from_dist`~.

2019-09-27 06:55 UTC, kinnison requested changes
Hi!

Thanks for your submission.  Just a rename of a variable (or some boolean sense inversions) to do and this looks mergeable from there!

D.

2019-09-27 06:55 UTC, kinnison commented on src/dist/manifestation.rs
> +            let notification = if explicit_modify {
Should this not be `if !explicit_modify {` ?  It seems to me that only implicit modifications (i.e. toolchain updates) should trigger the `RemovingOldComponent` variant.

2019-09-27 06:55 UTC, kinnison commented on src/dist/manifestation.rs
> +            let notification = if explicit_modify {
i.e. I think you've got the boolean sense of this variable backwards -- If you call it `explicit_modify` as you have, then you need to invert this test and the true/false at the callsites.  Alternatively call it `implicit_modify` and it'll be good as-is :D

2019-09-27 15:10 UTC, BeniCheni commented
> Alternatively call it `implicit_modify` and it'll be good as-is :D

Thank you, @kinnison. `implicity_modify` indeed sounds fit, and less risk not having to change the logic inversion in calling code & break something accidentally.

[1844a92](https://github.com/rust-lang/rustup.rs/pull/2016/commits/1844a92a75f2ae2ade759513041a097df4ebeae8) updated to use `implicity_modify`.

2019-09-27 16:44 UTC, kinnison approved these changes
Works for me. :+1:

Thank you, I'll just wait for the CI

2019-09-27 16:45 UTC, merged