cli: Allow specifying multiple component or target values in one argument
rust-lang/rustup pull request #2239
Opened 2020-02-25 19:06 UTC by jplatte

It has happened a few times to me now that I've tried to install a toolchain with `rustup toolchain install <toolchain> -c a,b,c`, only to get an error that the component "a,b,c" does not exist.

This PR changes the meaning of that command to the (IMO obvious) one of installing the toolchain `<toolchain>` with components `a`, `b` and `c`. Targets can also be specified in one `-t` argument when delimited with commas.

2020-02-27 19:43 UTC, kinnison requested changes
Nominally this change is good, however if we want to guarantee to support this going into the future then we need a test to demonstrate the functionality.  Could you please sort a test out (probably in cli-v2 or cli-misc) and push it to the PR?

2020-02-27 20:44 UTC, jplatte commented
I've added tests for `rustup`, should I create additional ones for `rustup-init`?

2020-03-04 20:16 UTC, payload approved these changes

2020-03-04 20:16 UTC, payload approved these changes

2020-03-08 09:47 UTC, kinnison requested changes
This looks good,  However as you note, there are changes in `setup_mode.rs` which do need verifying too.

Please try and a test to confirm the behaviour in the installer.

2020-03-15 16:06 UTC, jplatte commented
@kinnison Done.

2020-03-17 17:31 UTC, kinnison approved these changes

2020-03-17 17:31 UTC, merged