shows (override) in toolchain list
rust-lang/rustup pull request #2312
Opened 2020-04-28 08:48 UTC by LucianoBestia

This PR is for issue https://github.com/rust-lang/rustup/issues/2295
The command list now shows the override toolchain for this specific directory):

```bash
$home/bin/rustup toolchain list
stable-x86_64-unknown-linux-gnu (default)
nightly-x86_64-unknown-linux-gnu

$home/bin/rustup override set stable

$ home/bin/rustup toolchain list
stable-x86_64-unknown-linux-gnu (default) (override)
nightly-x86_64-unknown-linux-gnu

$home/bin/rustup override set nightly

home/bin/rustup toolchain list
stable-x86_64-unknown-linux-gnu (default)
nightly-x86_64-unknown-linux-gnu (override)
```

2020-04-28 19:26 UTC, kinnison commented
The examples look good, but I'd like to see some tests added to check all the cases (e.g. override by `rust-toolchain` vs. override by path etc.)

I think the tests probably belong in `cli-misc.rs`

2020-05-05 10:40 UTC, LucianoBestia commented
I found a similar test in cli-rustup.rs: list_default_toolchain()
So there I added 2 tests for list override:
- list_override_toolchain()
- list_default_and_override_toolchain()

2020-05-05 11:15 UTC, LucianoBestia commented
I think OverrideReason is not needed for the `rustup toolchain list` command.
The user is informed about the override.
For more details he could find elsewhere maybe in `rustup override list`?
But if needed I could add the OverrideReason to the string "(override)":
```rust
#[derive(Debug)]
pub enum OverrideReason {
    Environment,
    CommandLine,
    OverrideDB(PathBuf),
    ToolchainFile(PathBuf),
}

impl Display for OverrideReason {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> std::result::Result<(), fmt::Error> {
        match self {
            Self::Environment => write!(f, "environment override by RUSTUP_TOOLCHAIN"),
            Self::CommandLine => write!(f, "overridden by +toolchain on the command line"),
            Self::OverrideDB(path) => write!(f, "directory override for '{}'", path.display()),
            Self::ToolchainFile(path) => write!(f, "overridden by '{}'", path.display()),
        }
    }
}
```

2020-05-05 11:23 UTC, LucianoBestia commented
The real command for getting the details about OverrideReason is this:
`rustup show active-toolchain`
result:
`nightly-x86_64-unknown-linux-gnu (directory override for '/mnt/c/Users/Luciano/rustprojects/rustfmt')`

2020-05-08 09:53 UTC, kinnison commented
This is looking really good.  Could you please rebase to squash everything down to one or two neat commits, rather than the formatting nightmare you appear to have had in the middle, and then we should be good to merge.  I'm fine with the hint, `rustup show` will suffice as you say.

2020-05-08 09:54 UTC, kinnison requested changes
Approved modulo rebase/squash cleanup of commits and commit messages.

2020-05-27 07:15 UTC, LucianoBestia commented
I made the requested changes. Is it now ok to merge?

2020-05-30 18:41 UTC, kinnison approved these changes

2020-05-30 18:41 UTC, kinnison commented
Looks good :+1:

2020-05-30 18:41 UTC, merged