#2572 - Add defaults to common::question_*
rust-lang/rustup pull request #2605
Opened 2020-12-11 01:14 UTC by garethhubball

Hopefully this is cleaner than specifying the default as a string in each use of the `common::question_{str|bool}` functions.

2020-12-11 02:56 UTC, garethhubball commented
Fixes #2572

2020-12-11 19:14 UTC, kinnison commented
This covers the last of four questions - is there other work you have planned for the other questions hilighted in the issue you're fixing?

2020-12-11 19:14 UTC, kinnison commented
Also I wonder if we might get a cli-exact test to cover this perhaps?

2020-12-11 19:17 UTC, garethhubball commented
I'll have a look at how to write those, this covers all 4 of the questions by adding the default to the end.

2020-12-12 10:08 UTC, kinnison commented
So it does, I missed the effect of the first hunk.  If we don't have any cli-exact tests doing prompted configuration then it ought to be fairly easy to add.  If you want any help with that, ping me on Discord and if I'm around I'll do my best.

2020-12-12 16:35 UTC, garethhubball commented
Would it make more sense to do those tests in `cli-inst-interactive.rs` as it seems to be about testing the installation process? That, and it has the work done already for taking inputs.

2020-12-13 10:40 UTC, kinnison requested changes
The tests look good.  Thank you for that.

This does indeed seem to do exactly what it says on the tin.  It should indeed resolve the issue you set out to fix.

Before I can merge it I would like the commits cleanly rebased.  A commit for the tests and a commit for the functionality would be best.  Your choice which order to put them in.

If you need help doing that, ping me.  Also if you're having difficulty with vscode formatting stuff, check that 'Editor: Format On Safe' is set and that 'Editor: Format On Save Mode' is set to 'file'.

2020-12-14 22:20 UTC, kinnison approved these changes
:+1: thank you

2020-12-14 22:20 UTC, merged