Handle modifying rc files that don't have a trailing newline
rust-lang/rustup pull request #2667
Opened 2021-02-16 22:15 UTC by mythmon

This changes the flow so that instead of checking if `&rc.is_file`, it just tries to read the file and handles the error. I think this an ok way to handle it, though it might produce a little more IO. It simplifies the logic a lot.

I couldn't find any tests that cover this function, and I'm not comfortable adding tests right now, but I could try and tackle that with some guidance, or if there is a similar test I could use an example.

2021-02-16 22:59 UTC, mythmon commented
I found the tests in the CI build, and added one for this. I ran `cargo test` before pushing this PR. Any idea why it didn't run that test?

2021-02-20 10:36 UTC, kinnison commented
I'm not sure why the test didn't run for you locally, you can clearly see it running in CI here - https://github.com/rust-lang/rustup/pull/2667/checks?check_run_id=1914524215#step:17:1345

2021-02-20 10:43 UTC, kinnison requested changes
One potential tweak to be done to coments in the tests, and a `break` which I *think* should be a `continue`

Otherwise this looks good, thank you for making the effort to contribute.

2021-02-20 10:43 UTC, kinnison commented on src/cli/self_update/unix.rs
> +                Ok(contents) if contents.contains(&source_cmd) => break,
I fear this `break` ought to be `continue` so that it considers the other rc files.

2021-02-20 10:43 UTC, kinnison commented on tests/cli-paths.rs
> +            expect_ok(config, &INIT_NONE);
Why are you running rustup-init twice here?  As in, it's worth putting a coment in to explain what's going on, i.e. what we're trying to ensure does not rear its head once more.

2021-02-22 18:12 UTC, kinnison requested changes
This content is looking excellent, thank you for the extra test too, that is very useful.

Could you rebase the commits so that it's a clean change, and then we can look to merge this.

Thank you for your work.

2021-02-22 18:32 UTC, mythmon commented
Alright, rebased and squashed down to one commit. Thanks for the review and guidance!

2021-02-22 18:36 UTC, kinnison approved these changes
:+1:

I'll merge on green-CI

2021-02-22 18:55 UTC, merged