uninstalls toolchains prior to deleting the rustup home folder
rust-lang/rustup pull request #2864
Opened 2021-10-09 22:23 UTC by Darunada

Fixes #2789 

I was able to reproduce the issue, and with this change the command now succeeds with the following output.

```
C:\Users\Lea>rustup self uninstall

Thanks for hacking in Rust!

This will uninstall all Rust toolchains and data, and remove
%USERPROFILE%\.cargo/bin from your PATH environment variable.

Continue? (y/N) y

info: removing toolchains
info: uninstalling toolchain nightly-x86_64-pc-windows-msvc
info: toolchain nightly-x86_64-pc-windows-msvc uninstalled
info: uninstalling toolchain stage2
info: toolchain stage2 uninstalled
info: removing rustup home
info: removing cargo home
info: removing rustup binaries
info: rustup is uninstalled
```

2021-11-08 11:14 UTC, kinnison requested changes
I'd like to see at least one test validating that this uninstall is happening.  Probably it ought to be a new test in `tests/cli-self-upd.rs` something like an `fn uninstall_removes_installed_toolchains()`

2021-11-22 16:59 UTC, Darunada commented
sure thing, work has gotten a bit more stressful in the last couple weeks, I will try to do something this weekend

2022-09-30 02:11 UTC, hi-rustin commented
@Darunada Do you still have time to advance it? If you don't have time I would be happy to help add that test. But it would be great if you could move forward. Thanks!

2023-02-25 21:41 UTC, Darunada commented
Sorry for the delay, I went ahead and added a test.  Let me know if you like the approach!

2023-06-13 01:51 UTC, hi-rustin requested changes

2023-06-13 01:51 UTC, hi-rustin commented on src/cli/rustup_mode.rs
> +fn self_uninstall(cfg: &Cfg, m: &ArgMatches<'_>) -> Result<utils::ExitCode> {
I think we don't have a lifetime argument here.

2026-03-16 03:47 UTC, Darunada commented
Hello team, I am once again prepared for your reconsideration

2026-03-16 08:44 UTC, djc approved these changes
Mostly LGTM, thanks for updating after all those years!

(Please also squash your changes into a single commit.)

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rustup/2864/58e6f99a43c749fd61097f21154dc6571720d0b5..d3d8f5f1d78cf466577cb66d827134e427fd2321)*

2026-03-16 08:44 UTC, djc commented on src/cli/self_update.rs
> +    cfg: &Cfg<'_>,
Tiny nit: this argument can replace `process` (which is accessible via `cfg`), and please keep it last.

2026-07-08 06:39 UTC, rami3l approved these changes

2026-07-08 06:40 UTC, rami3l commented on src/cli/self_update.rs
Nit: Just to make it clearer, please also update the doc string to reflect the new behavior :)

*[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rustup/2864/1905e89964620b32336c617c7ea52f4725ac922b..239a9e131ec5a813271dcca9b0cf9cbb4a7be2b6)*

2026-07-08 07:34 UTC, merged