Remove trailing slashes in toolchain name
rust-lang/rustup pull request #2897
Opened 2021-11-10 11:43 UTC by sathwikmatsa

This PR fixes #2873

2021-11-11 10:01 UTC, kinnison requested changes
There's a commit which needs removing; also also we need a test to demonstrate the issue and then demonstrate it is resolved by this patch.  If you need some inspiration, check out cli-v2.rs which should have plenty of example tests you can crib from.

Thank you for your effort.

2021-11-11 10:01 UTC, kinnison commented on tests/mock/clitools.rs
> +    let mut arg_strings: Vec<Box<str>> = vec![name.to_owned().into_boxed_str()];
This change is unrelated to this piece of work, please drop the "ok clippy" commit, it's not necessary for this.

2021-11-19 14:47 UTC, hi-rustin approved these changes
LGTM. But could you please squash your commits?

2021-12-02 11:54 UTC, kinnison approved these changes
This looks good, sorry for the delay

2021-12-02 11:54 UTC, merged