Suggest right toolchain when running clippy
rust-lang/rustup pull request #3338
Opened 2023-04-27 01:59 UTC by hi-rustin

We should use beat as we discussed before.

2023-04-27 05:17 UTC, rbtcollins commented on CONTRIBUTING.md
> +3. Submit a pull request :D
Is the renumbering deliberate, or a side effect of some editor plugin? These steps are still part of the sequence started on line 3.

2023-04-27 05:17 UTC, rbtcollins requested changes
.

2023-04-27 13:07 UTC, 0xPoe commented on CONTRIBUTING.md
> +3. Submit a pull request :D
Oops. Updated by my markdown linter. Reverted!

2023-04-30 08:15 UTC, rbtcollins approved these changes

2023-04-30 08:15 UTC, merged