Fix compile on rust nightly
rust-lang/rustup pull request #3364
Opened 2023-05-25 03:52 UTC by heiher

This PR fixes compile on rust nightly (1.71-dev).

### Compile errors

```
error: cannot find macro `lazy_static` in this scope
   --> download/src/lib.rs:345:5
    |
345 |     lazy_static! {
    |     ^^^^^^^^^^^
    |
    = help: consider importing this macro:
            lazy_static::lazy_static
    = note: `lazy_static` is in scope, but it is a crate, not a macro

error[E0425]: cannot find value `CLIENT_DEFAULT_TLS` in this scope
   --> download/src/lib.rs:379:37
    |
379 |             TlsBackend::Default => &CLIENT_DEFAULT_TLS,
    |                                     ^^^^^^^^^^^^^^^^^^ not found in this scope

For more information about this error, try `rustc --explain E0425`.
```

2023-05-25 03:56 UTC, xen0n reviewed
In my own experiments this only happens with the `reqwest-rustls-tls` feature disabled but `reqwest-backend` and `reqwest-default-tls` enabled. Given the context of your work that's `loongarch64` enablement, maybe mentioning the intended use case (no `ring` yet, so no `reqwest-rustls-tls`) would further justify the change.

2023-05-26 01:42 UTC, heiher commented
r? @hi-rustin

2023-05-28 06:04 UTC, rbtcollins requested changes

2023-05-28 06:04 UTC, rbtcollins commented on download/src/lib.rs
> -    #[cfg(feature = "reqwest-rustls-tls")]
Please just pub a `any` in here with the additional feature that requires rustls.

2023-05-28 18:52 UTC, merged