Remove rls and rust-analysis from components list.
rust-lang/rustup pull request #3410
Opened 2023-07-17 16:22 UTC by burakemir

RLS was deprecated over a year ago. https://blog.rust-lang.org/2022/07/01/RLS-deprecation.html
The rust-analysis component seems to only contain a placeholder file with the contents

```
{"warning": "The `rust-analysis` component has been removed." }"
```

I checked a few occurrences in rustup toolchain manifest files, and they only seem to contain that "removed.json".

I believe no one will miss these things.

2023-07-18 23:47 UTC, hi-rustin commented
cc: https://github.com/rust-lang/rustup/issues/3316

2023-07-18 23:52 UTC, 0xPoe approved these changes
Looks good  to me.

2023-07-18 23:53 UTC, hi-rustin commented
@burakemir Please rebase your branch with the latest master branch to fix the test.

2023-08-15 07:36 UTC, rbtcollins commented
I think we should rearrange rather than remove these entries. Rustup installs both current and old versions of toolchains, and those components remain valid in older releases: the removal only affects newer channel metadata, not existing.

Something like 
```
### Previous components

These components have been deprecated and are not published in new Rust releases.

<table here>
```

2023-08-20 06:01 UTC, rbtcollins requested changes
Changes requested in my other comment

2023-08-20 13:34 UTC, burakemir commented
Done.

2023-08-21 08:10 UTC, djc approved these changes

2023-12-18 08:04 UTC, closed without merging